### ISSUE TITLE
Add branch/23.08

### ISSUE THREAD

**Issue by cxrvh** [flathub/org.freedesktop.Sdk.Extension.openjdk11#42]
openjdk11 should be build for 23.08 when the new runtime is released.
I've already prepared a [branch](https://github.com/cxrvh/org.freedesktop.Sdk.Extension.openjdk11/tree/branch/23.08) for the current 23.08beta which can be updated after the release.

**Comment by guihkx** [comment]
I just noticed that the 23.08 branch has been created.

Maybe you can now send a pull request with your changes for proper reviewing? Though it's a bit unfortunate that the maintainers seem a little unresponsive (given the number of open pull requests with no comments or reviews)...

Speaking of maintainers, I think they should update the default branch to point to 23.08 instead of 21.08, which is essentially EOL now.

**Comment by hfiguiere** [comment]
sorry I didn't notice a branch for the beta.

**Comment by hfiguiere** [comment]
the branch just changed the runtime versions from the tip of 22.08, so nothing else was touched.
